### ISSUE TITLE
Black shoes too dark and soles too shiny

### ISSUE THREAD

**Issue by AndrewRH** [RenderHeads/z84530x125#1]
They're basically black now, with bright white highlights..  Needs some sort of ambient colour so they aren't so black, or make them a bit less glossy?

Also some of the soles are too reflective, check this...

Affects looks:

- [x] B101
- [x] B103
- [x] B104
- [x] B107
- [x] B201
- [x] B203
- [x] B205   (also Albedo texture on shoe seems missing or something as can't see the rings for the laces)
- [x] B301
- [x] B303
- [x] B304B
- [x] B305
- [x] B307
- [x] B305
- [x] B308
- [x] B503  (this is only the soles that are too shiny)
- [x] B504B  (this is only the soles that are too shiny)
- [x] B505  (this is only the soles that are too shiny)
- [x] B604A  (this is only the soles that are too shiny)

**Comment by ElzethCalitz** [comment]
Fixed the albedo problem for B205 
Corrected the specular maps for B503, B504B, B505 and B604A
Toned down specular value and added a higher bump for B101, B104, B107, B301, B304B, B305 (kitten heels)
Toned down specular value B103, B201, B203, B205, B303, B307 and B308

**Comment by MorrisRH** [comment]
B103, B201, B205, B303, B307, B308 have too much specular highlighting on the underside of the sole, you get very bright hi-lights on the sides of the chunky tread

**Comment by davidhecker-rh** [comment]
@ElzethCalitz See above.

**Comment by ElzethCalitz** [comment]
Painted darker colour on the specular maps for B103, B201, B205, B303, B307 and B308 to resolve specular value brightness on the sole and underneath the shoe itself.

**Comment by MorrisRH** [comment]
@ElzethCalitz B201 looking good, can the same be applied to B203 please

**Comment by ElzethCalitz** [comment]
Fixed B203 to look like B201
