### ISSUE TITLE
B604A - Distortion when arms raised

### ISSUE THREAD

**Issue by AndrewRH** [RenderHeads/z84530x125#10]
![image](https://user-images.githubusercontent.com/5418126/67246535-fa014080-f45e-11e9-9cf2-13a942f5bc3d.png)

**Comment by MorrisRH** [comment]
Still a mess under the arms

**Comment by ShaneRH** [comment]
did another pass on this, please test

**Comment by KellyMAM** [comment]
Still there on the left
