### ISSUE TITLE
B603 - Bent elbows collapse & underarm stretching & intersecting at bottom of shirt

### ISSUE THREAD

**Issue by AndrewRH** [RenderHeads/z84530x125#11]
![image](https://user-images.githubusercontent.com/5418126/67246685-6da34d80-f45f-11e9-998a-a17a3fde2643.png)

- [x]  Bent elbows
- [x]  Underarms
- [x]  Bottom of shirt intersections

**Comment by SteUK** [comment]
Bottom intersection is fixed

**Comment by MorrisRH** [comment]
Looking good!
