### ISSUE TITLE
B602 - Cloth needs better falloff when raising legs, currently crumbles the shirt badly

### ISSUE THREAD

**Issue by AndrewRH** [RenderHeads/z84530x125#12]
![image](https://user-images.githubusercontent.com/5418126/67246877-ffab5600-f45f-11e9-8d81-51dc9d15ab9b.png)

**Comment by AndrewRH** [comment]
![image](https://user-images.githubusercontent.com/5418126/67246955-397c5c80-f460-11e9-8b53-430d8872e9c1.png)

**Comment by ridhoRH** [comment]
checked in a fix for the shirt crumpling, still need to add colliders to fix intersections

**Comment by ridhoRH** [comment]
checked in some collider updates to try and get the shirt to intersect less. still needs work

**Comment by ridhoRH** [comment]
![image](https://user-images.githubusercontent.com/40686656/67392994-d2ff5780-f5a1-11e9-9e45-acbca5b310e0.png)

some skinning issues when cloth is turned off

**Comment by ElzethCalitz** [comment]
Skinning fixed
