### ISSUE TITLE
B601 - Knees and elbows need better skinning

### ISSUE THREAD

**Issue by AndrewRH** [RenderHeads/z84530x125#14]
![image](https://user-images.githubusercontent.com/5418126/67247197-e9ea6080-f460-11e9-8be6-e2514aad0839.png)

**Comment by ShaneRH** [comment]
![image](https://user-images.githubusercontent.com/18391483/67363774-5f902280-f56e-11e9-90a5-4156ec7f90a3.png)

![image](https://user-images.githubusercontent.com/18391483/67363788-66b73080-f56e-11e9-9722-fd10fd2e630d.png)
