### ISSUE TITLE
Shoe normals need smoothing

### ISSUE THREAD

**Issue by AndrewRH** [RenderHeads/z84530x125#2]
These shoe normals need smoothing, they're showing the faces at the moment
- [x] B401
- [x] B402
- [x] B405
- [x] B501

**Comment by davidhecker-rh** [comment]
@AndrewRH Does this only affect those four looks? These shoes are also used on:
B5/04 A
B6/03
B6/04 B
B6/05

**Comment by AndrewRH** [comment]
Yup, we checked all the other looks and it's just the ones i listed

**Comment by AndrewRH** [comment]
B401:
![image](https://user-images.githubusercontent.com/5418126/67270892-d15a6480-f4b9-11e9-89cb-ea98c3523187.png)

B504A:
![image](https://user-images.githubusercontent.com/5418126/67270912-db7c6300-f4b9-11e9-89f1-dcd69927c2bf.png)

**Comment by ElzethCalitz** [comment]
Fixed the normals on B401,  B402, B405 and B501
