### ISSUE TITLE
B504A - Weird triangle appears on the back right shoulder area

### ISSUE THREAD

**Issue by AndrewRH** [RenderHeads/z84530x125#23]
Not sure if this is skinning or cloth related.  Can't seem to replicate in editor but we saw it on the screen during the walk cycle I believe.  Need to get a screenshot...

**Comment by SteUK** [comment]
As you say, cannot see in the editor :/  I have optimied the colliders and made sure the cloth weights on the top half of the jumper are all zero.

**Comment by SteUK** [comment]
I think re-test this one please :)
