### ISSUE TITLE
B503 - Underarm skinning needed - lots of stretching and corruption

### ISSUE THREAD

**Issue by AndrewRH** [RenderHeads/z84530x125#24]
![image](https://user-images.githubusercontent.com/5418126/67249163-f2459a00-f466-11e9-94f4-27c3c83b36b2.png)

![image](https://user-images.githubusercontent.com/5418126/67249199-1acd9400-f467-11e9-8f78-dce1dc2c25cf.png)

**Comment by KellyMAM** [comment]
The cloth is causing this weird tearing but cleaned up skinning
