### ISSUE TITLE
B503 - Grey shirt looks too dark

### ISSUE THREAD

**Issue by AndrewRH** [RenderHeads/z84530x125#25]
Compare to reference
Might just be because it is surrounded by a bright jacket....

**Comment by AndrewRH** [comment]
![image](https://user-images.githubusercontent.com/5418126/67249254-57998b00-f467-11e9-8d5c-38946c3b36dd.png)

From a distance it certainly looks closer to black....

**Comment by davidhecker-rh** [comment]
@AndrewRH How does it look on B505 as that has the same colour undershirt?

**Comment by AndrewRH** [comment]
![image](https://user-images.githubusercontent.com/5418126/67269909-dd452700-f4b7-11e9-9000-492b1b268fc7.png)

![image](https://user-images.githubusercontent.com/5418126/67269922-e59d6200-f4b7-11e9-9ff0-27c3dba175e0.png)

**Comment by davidhecker-rh** [comment]
Those do look like different colour undershirts there, with B505 looking blue instead of grey. @NadiaDK can you please check if the correct undershirt colour is assigned to B505?

**Comment by MorrisRH** [comment]
B505 looks blue
B503 grey shirt looking good

**Comment by MorrisRH** [comment]
Grey still too dark, here's the reference
![image](https://user-images.githubusercontent.com/46530460/67315513-04771500-f507-11e9-896a-6953796837cc.png)

**Comment by MorrisRH** [comment]
@NadiaDK Looking at it here on our screens it looks ok, but on the wall it looks too dark. Can you just make it about 20-30% brighter?
