### ISSUE TITLE
B501 - When raising legs cloth could be better

### ISSUE THREAD

**Issue by AndrewRH** [RenderHeads/z84530x125#28]
![image](https://user-images.githubusercontent.com/5418126/67249515-38e7c400-f468-11e9-9364-7230058c55dc.png)

**Comment by SteUK** [comment]
Tired and failed to make this better.  The leg shape is awkward and the jeans don't go up very high. Plus there is a t-shirt under the jumper that wants to intersect!

**Comment by ridhoRH** [comment]
![image](https://user-images.githubusercontent.com/40686656/67373064-43e14800-f57f-11e9-8db1-e84aef073a70.png)

@ShaneRH 
weird skinning on the t-shirt. not a big issue but it seems to bleed through a little bit when the legs are raised.

**Comment by ridhoRH** [comment]
closing as this issue was solved in #26
