### ISSUE TITLE
B405 - Shirt appears too bright/white

### ISSUE THREAD

**Issue by AndrewRH** [RenderHeads/z84530x125#29]
Either it doesn't have the correct texture/material,
or it is the look lighting mode setting that needs tweaking

**Comment by ElzethCalitz** [comment]
The look is set as a dark look. We deliberately did not texture this shirt pure white, but if I make this more grey it will look like a light grey shirt and not a white shirt anymore. Is there a way this can be sorted out with lighting? If not I am happy to take a look at his again

**Comment by MorrisRH** [comment]
The lighting has been improved and now the shirt is looking fine 👍
