### ISSUE TITLE
Beanie darken the inside material and try to make material less reflective

### ISSUE THREAD

**Issue by AndrewRH** [RenderHeads/z84530x125#3]
- [ ] B106A
- [ ] B203
- [ ] B307
- [ ] B203
- [ ] B401
- [ ] B404A
- [ ] B405
- [ ] B603

**Comment by ElzethCalitz** [comment]
I have set it to the max darkness and lowest possible specular value on the inside of all these beanies.

**Comment by AndrewRH** [comment]
Max darkness?  Is that what looks best? :)

**Comment by MorrisRH** [comment]
still suffering from some lighting issue but better overall
