### ISSUE TITLE
B403 - Skinning/mesh issues

### ISSUE THREAD

**Issue by AndrewRH** [RenderHeads/z84530x125#38]
![image](https://user-images.githubusercontent.com/5418126/67250236-e4921380-f46a-11e9-9658-8e29d70bdee7.png)

![image](https://user-images.githubusercontent.com/5418126/67250248-f4115c80-f46a-11e9-8976-1078c8c17a55.png)

![image](https://user-images.githubusercontent.com/5418126/67250264-025f7880-f46b-11e9-8141-1e59c83517ac.png)

![image](https://user-images.githubusercontent.com/5418126/67250280-0db2a400-f46b-11e9-890c-9cd7a6d3f8c1.png)

**Comment by NadiaDK** [comment]
Under arm section and collar has been adjusted. Minor cleaning was done at the bottom where the shirt lifts up. The section where the jeans and shirt meet, will need adjustments on the cloth simulation first before possible further revision can be made on the weight painting as discussed with Rhido in the office
