### ISSUE TITLE
B402 - Scarf issues

### ISSUE THREAD

**Issue by AndrewRH** [RenderHeads/z84530x125#39]
![image](https://user-images.githubusercontent.com/5418126/67250373-6a15c380-f46b-11e9-8524-6c0663952c47.png)

- [ ] Scarf is rooted to the shoulder (not Spine2)?
- [ ] Looks like it's falling off the neck

**Comment by SteUK** [comment]
Not sure what it should be fixed to....

**Comment by ShaneRH** [comment]
weights scarf to neck

**Comment by MorrisRH** [comment]
Looks good to me
