### ISSUE TITLE
Missing/broken attachments

### ISSUE THREAD

**Issue by AndrewRH** [RenderHeads/z84530x125#4]
- [x] B304A (add rivets)
- [x] B305 (add rivets)
- [x] B307 (all attachments broken, zips, rivets etc)
- [x] B604B (missing buttons)
- [x] B304B (no buttons yet)
- [x] B401 (top buttons are inside the model, need to be snapped again?)
- [x] B402 (buttons need some one the other side, and material to be metallic)
- [x] B403 (says buttons prefab is missing)
- [x] B405 (buttons need some one the other side, and material to be metallic)
- [x] B503 (buttons seem light, shouldn't they be closer to the jacket colour?)
- [x] B601 (top middle button needs shifting to one side, it's too much in the middle and is intersecting both sides of the shirt)
- [x] B602 (top middle button needs shifting to one side, it's too much in the middle and is intersecting both sides of the shirt)

- [x] B305+B307+B402 - attachments suddenly the material is missing

**Comment by AndrewRH** [comment]
Hey B305 - rivets suddenly the material is missing :)

**Comment by ElzethCalitz** [comment]
Adjusted the button colour for B401 and B503

**Comment by ridhoRH** [comment]
Updated materials & B405

**Comment by MorrisRH** [comment]
B307 rivets are missing their material
B604B buttons on back of jacket are offset
B601, B602 button issue fixed but button looks like it's on the wrong side
B403 same button issue as B601
B401 buttons still very blue
@KellyMAM B402, B405 buttons look odd? (B402 very broken overall though)

**Comment by ridhoRH** [comment]
Updated rivets again, moved B601/2/403 button to the left side

**Comment by ridhoRH** [comment]
Need more info on this one please: B402, B405 buttons look odd? (B402 very broken overall though)
perhaps some images as to what is wrong?

Is it because the scarf is clipping through it?

**Comment by AndrewRH** [comment]
B402 and B405 look not bad actually - we just checked the reference...But they're an odd colour and should be metallic.  Also there shoudl be some on the other side of the jacket too.  See reference:

![image](https://user-images.githubusercontent.com/5418126/67290672-be0ebf80-f4e0-11e9-93ae-95eaa12c834b.png)

**Comment by ElzethCalitz** [comment]
![Capture](https://user-images.githubusercontent.com/54107152/67291423-ce736a00-f4e1-11e9-9a87-61e26cc0e4e1.PNG)

From what we can see on our side the buttons for B41 matches the shirt colour, like it is in the reference. Not sure how to change it since we do not see what you guys see. If you can advise on this I can have a look at it again

**Comment by AndrewRH** [comment]
I've unticked B401 - top buttons are inside the model, need to be snapped again?

**Comment by ElzethCalitz** [comment]
Updated B402 and B405 button material

**Comment by ridhoRH** [comment]
Added more rivets on B402/B405

**Comment by ridhoRH** [comment]
re-snapped B401's buttons

**Comment by MorrisRH** [comment]
Fixing up B402/405's rivets here
