### ISSUE TITLE
B402 - Cloth issues

### ISSUE THREAD

**Issue by AndrewRH** [RenderHeads/z84530x125#40]
Many intersections and artifacts

![image](https://user-images.githubusercontent.com/5418126/67250420-9c272580-f46b-11e9-89a9-98e9226ff9d8.png)
![image](https://user-images.githubusercontent.com/5418126/67250461-cd075a80-f46b-11e9-9305-3571a024ed05.png)

**Comment by SteUK** [comment]
Fixed in the main.  Scarf needs some work but this will be done post bone fixes and is bugged elsewhere.

**Comment by MorrisRH** [comment]
Mesh needs fixing first I think... leaving this one open

**Comment by SteUK** [comment]
Have another look...I have tweaked. Might not need mesh change.

**Comment by MorrisRH** [comment]
Issue with the hood
![Image from iOS](https://user-images.githubusercontent.com/46530460/67308773-ffac6400-f4fa-11e9-9286-c6d40572e5c4.jpg)

**Comment by KellyMAM** [comment]
I've updated the skinning so @SteUK if you could check that the scarf and cloth is still working as they should

**Comment by KellyMAM** [comment]
This is in a different issue #77
