### ISSUE TITLE
B401 - Cloth issues

### ISSUE THREAD

**Issue by AndrewRH** [RenderHeads/z84530x125#41]
Cloth intersections, especially when walking at the back of the jacket and on the right middle with body

**Comment by SteUK** [comment]
Fixed the intersection on the front.

The back ones I cannot see.  At the bottom on the back you can see the white t-shirt under (not intersecting) the jacket.  Maybe this was being mistaken for an intersection?

![image](https://user-images.githubusercontent.com/7014856/67264271-ed0a3e80-f4aa-11e9-92d0-f4639566e117.png)

**Comment by MorrisRH** [comment]
Still intersecting at the front

**Comment by SteUK** [comment]
Try again :S

**Comment by ridhoRH** [comment]
fixed the bits at the bottom of cloth that was still intersecting.
fixed the bits of the cloth at the bottom that wasn't working

**Comment by MorrisRH** [comment]
still a couple of small intersections

<img width="277" alt="B401" src="https://user-images.githubusercontent.com/46530460/67400292-b9640d00-f5ad-11e9-9222-bc199db75f06.png">

**Comment by ridhoRH** [comment]
tried to fix this a bit more
