### ISSUE TITLE
B401 - Skinning

### ISSUE THREAD

**Issue by AndrewRH** [RenderHeads/z84530x125#42]
Back of the legs - so try make the shirt not move so much when the legs move

![image](https://user-images.githubusercontent.com/5418126/67250584-430bc180-f46c-11e9-9468-e3f60c366729.png)

**Comment by ShaneRH** [comment]
![bacj_walk](https://user-images.githubusercontent.com/18391483/67365466-ff9b7b00-f571-11e9-8283-883c9cb6cfca.gif)

**Comment by KellyMAM** [comment]
Much better
