### ISSUE TITLE
B101 - Cloth intersections and skinning

### ISSUE THREAD

**Issue by AndrewRH** [RenderHeads/z84530x125#43]
- [x] Cloth intersects the characters left shoulder, and a bit of the right too. 
- [x]  Also skinning on the elbows collapses

**Comment by SteUK** [comment]
This is a skinning issue.  I have checked the cloth constraints at the intersection points and they are all zero.

**Comment by MorrisRH** [comment]
cloth intersection with back of right leg on walk out

**Comment by MorrisRH** [comment]
Skinning issue on lapels

![IMG_1898](https://user-images.githubusercontent.com/46530460/67304692-7eea6980-f4f4-11e9-9251-b0bab57219b9.jpg)

![IMG_1897](https://user-images.githubusercontent.com/46530460/67304725-8f024900-f4f4-11e9-9b42-e1c71a862591.jpg)

**Comment by kahnivore** [comment]
fixed lapel intersection

**Comment by KellyMAM** [comment]
Elbows need skinning updated and there is a harsh fall off on the chest when moving the shoulders apart

**Comment by kahnivore** [comment]
uupdated elbows - think chesk was already done

**Comment by MorrisRH** [comment]
lapels stretch badly when arms raised
<img width="278" alt="B101" src="https://user-images.githubusercontent.com/46530460/67395943-11e3dc00-f5a7-11e9-8006-ed962ae6fdc7.png">

**Comment by KellyMAM** [comment]
This is good enough
