### ISSUE TITLE
B103 - Cloth intersections and skinning 

### ISSUE THREAD

**Issue by AndrewRH** [RenderHeads/z84530x125#44]
- [ ] Cloth intersects the characters left shoulder, and a bit of the right too. 
- [ ]  Also skinning on the elbows collapses

**Comment by AndrewRH** [comment]
![image](https://user-images.githubusercontent.com/5418126/67251817-9bdd5900-f470-11e9-900b-8eeb0eb57f6f.png)

**Comment by SteUK** [comment]
The cloth weighing is all zero in this area. I could use colliders to push it out, but I think we are better relaxing the geometry away from the coat on the back in this area.

**Comment by MorrisRH** [comment]
Fixed

**Comment by KellyMAM** [comment]
There is still a little intersection when the arms are lift all the way up above the head

**Comment by KellyMAM** [comment]
Would also be nice to have a little more of a fall-off on the shoulder's weights

**Comment by ElzethCalitz** [comment]
Tried fixing fall off on shoulder and intersection
