### ISSUE TITLE
B106B - Cloth intersections - jeans waistline folded over

### ISSUE THREAD

**Issue by AndrewRH** [RenderHeads/z84530x125#46]
Jacket intersects jeans at back when walking

![image](https://user-images.githubusercontent.com/5418126/67251959-45244f00-f471-11e9-8d5a-c84daa797fff.png)

**Comment by AndrewRH** [comment]
Also in front
![image](https://user-images.githubusercontent.com/5418126/67252123-e7dccd80-f471-11e9-9b31-f9f946ac8396.png)

**Comment by SteUK** [comment]
Rear intersections setup and cloth improved a bit.

There seems to be a fold on the jeans waistline that isn't there until you 'run' an app/editor.

**Comment by ShaneRH** [comment]
I added another collider to resolve the bit in the front

**Comment by ShaneRH** [comment]
Couldn't replicate the  jeans waistline thing
