### ISSUE TITLE
B605 - Weird shape of body/shirt (skinning?)

### ISSUE THREAD

**Issue by AndrewRH** [RenderHeads/z84530x125#6]
Might be underarm skinning needed
The arms might be too close to the body also quite a weird shape from the shirt

**Comment by MorrisRH** [comment]
issues with skinning around the arms

**Comment by AndrewRH** [comment]
This images shows how weird the tshirt looks around the arms...
![image](https://user-images.githubusercontent.com/5418126/67392137-4c964600-f5a0-11e9-8627-1be140763845.png)

It might be to do with how the chest is pushed out:
![image](https://user-images.githubusercontent.com/5418126/67392291-9121e180-f5a0-11e9-895e-8ebf50018fe3.png)

There is also a general stretching problem on the back, especially on the right side, and even a bit of crumple:

![image](https://user-images.githubusercontent.com/5418126/67392433-cd554200-f5a0-11e9-8656-5e185523b769.png)

**Comment by KellyMAM** [comment]
I think I made it slightly better
