### ISSUE TITLE
B504A - Shoulder needs under shirt mesh change

### ISSUE THREAD

**Issue by SteUK** [RenderHeads/z84530x125#67]
The under shirt mesh needs pulling in a bot under the shoulders

![image](https://user-images.githubusercontent.com/7014856/67271382-b0deda00-f4ba-11e9-8e7a-d28d4ffbb8ba.png)

**Comment by ShaneRH** [comment]
screenshot is B504A?

**Comment by ShaneRH** [comment]
moved geo in, changed title to 504A so it matches the screenshot

**Comment by KellyMAM** [comment]
Looks good
