### ISSUE TITLE
Big jacket skinning issues (B402 + B405)

### ISSUE THREAD

**Issue by AndrewRH** [RenderHeads/z84530x125#70]
Needs cleaning up

**Comment by KellyMAM** [comment]
Elbows need better skinning

**Comment by ShaneRH** [comment]
B402
![image](https://user-images.githubusercontent.com/18391483/67389331-b3186580-f59a-11e9-8285-eaac52ab5e44.png)
![image](https://user-images.githubusercontent.com/18391483/67389339-b875b000-f59a-11e9-84b4-a05132a246be.png)

**Comment by ShaneRH** [comment]
B405
![image](https://user-images.githubusercontent.com/18391483/67390152-5a49cc80-f59c-11e9-9ade-bd9bf69aec8b.png)
![image](https://user-images.githubusercontent.com/18391483/67390164-60d84400-f59c-11e9-807f-ed4ffa477df4.png)

**Comment by KellyMAM** [comment]
B402 has cloth intersection between the white shirt and the jacket at the waist @SteUK
