### ISSUE TITLE
B304A - Elbows

### ISSUE THREAD

**Issue by MorrisRH** [RenderHeads/z84530x125#72]
Elbows crease badly

**Comment by ShaneRH** [comment]
I repainted the elbows

**Comment by MorrisRH** [comment]
@ShaneRH still creasing really badly

![B304A](https://user-images.githubusercontent.com/46530460/67322775-d3501200-f511-11e9-8e22-9539f39bd9f1.png)

**Comment by ShaneRH** [comment]
![image](https://user-images.githubusercontent.com/18391483/67360010-1f787200-f565-11e9-9332-1620444b7c5a.png)

Please try again

**Comment by KellyMAM** [comment]
Looks much better
