### ISSUE TITLE
B305 - Skinning

### ISSUE THREAD

**Issue by MorrisRH** [RenderHeads/z84530x125#73]
Intersection on the left side of the chest
![IMG_1900](https://user-images.githubusercontent.com/46530460/67307766-4c8f3b00-f4f9-11e9-9fa1-38a60907ffdc.jpg)

**Comment by ShaneRH** [comment]
The skinning was fine in that region. I added colliders to the  chest on the jacket, so hopefully this will reduce or resolve this issue.

**Comment by KellyMAM** [comment]
Still there, check that the weights on the spine joints arnt causing the issue. So bend the spine slighting and check if you can see the problem.

**Comment by ShaneRH** [comment]
@KellyMAM  I have copied the weights over

**Comment by MorrisRH** [comment]
Fixed
