### ISSUE TITLE
B505 - Intersection

### ISSUE THREAD

**Issue by MorrisRH** [RenderHeads/z84530x125#74]
Label intersects with back of the shirt when viewed from behind

**Comment by ShaneRH** [comment]
Caused by cloth, moved label forward and tested by rotating the neck joint in play mode. I was able to reduce the amount this was happening.

**Comment by KellyMAM** [comment]
The label of the overshirt is now going through the Tshirt when viewed from the front

**Comment by ElzethCalitz** [comment]
Fixed the label of the overshirt going through the Tshirt when viewed from the front
