### ISSUE TITLE
B604B - Inside edge of collar appears to glow, looks odd

### ISSUE THREAD

**Issue by AndrewRH** [RenderHeads/z84530x125#8]
![image](https://user-images.githubusercontent.com/5418126/67245940-7c890080-f45d-11e9-93f3-081207765c05.png)

Might be normals / mesh issue?

**Comment by KellyMAM** [comment]
Looks like the texture on the label is missing

**Comment by davidhecker-rh** [comment]
@ElzethCalitz See above.

**Comment by ElzethCalitz** [comment]
@KellyMAM 
As far as we can tell the label texture was on separate mesh, which is no longer there. So there is no label texture

**Comment by ElzethCalitz** [comment]
![image](https://user-images.githubusercontent.com/54107152/67385107-b6a7ee80-f592-11e9-9340-4055f251d25d.png)

**Comment by KellyMAM** [comment]
Oh I seeeee, I was looking at this section 
![image](https://user-images.githubusercontent.com/35454029/67389087-2b325b80-f59a-11e9-9431-c6ba3ce463e2.png)
