### ISSUE TITLE
Large shoe distortion

### ISSUE THREAD

**Issue by AndrewRH** [RenderHeads/z84530x125#9]
![image](https://user-images.githubusercontent.com/5418126/67246023-aa6e4500-f45d-11e9-8f42-039a1b72fb47.png)

- [ ] B503
- [ ] B504B
- [ ] B505
- [ ] B604A

Skinning needs cleaning up / hacking?

**Comment by KellyMAM** [comment]
tried cleaning up skinning, it didnt work. Fixing the animation is the only way to make this better
